$(document).ready(function(){
  $("#ss").hover(function(){
    $("#ss-detail").fadeIn(700);
  });
  $("#ct").hover(function(){
    $("#ct-detail").fadeIn(700);
  });
  $("#bltn").hover(function(){
    $("#bltn-detail").fadeIn(700);
  });
});
